jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install